halloDocMvc/Controllers/AdminPartialsController.cs
using AdminHalloDoc.Controllers.Login;
using CommandLine;
using HalloDoc.BAL.Interface;
using HalloDoc.DAL.Data;
using HalloDoc.DAL.DataModels;
using HalloDoc.DAL.ViewModals;
using HalloDoc.DAL.ViewModals.Access;
using HalloDoc.DAL.ViewModals.AdminDashBoardActions;
using HalloDoc.DAL.ViewModals.AdminDashBoardActions.NewRequestAction;
using HalloDoc.DAL.ViewModals.AdminDashBoardViewModels;
using HalloDoc.DAL.ViewModals.Partner;
using HalloDoc.DAL.ViewModals.Provider;
using HalloDoc.DAL.ViewModals.Records;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Diagnostics.Runtime.DacInterface;
using OfficeOpenXml;
using Org.BouncyCastle.Asn1.Ocsp;
using System.Reflection;
using System.Text;

namespace hellodocsrsmvc.Controllers
{
    //[adminauthentication]
    [AdminAuth("admin")]
    public class AdminPartialsController : Controller
    {
        enum adminRoles
        {
            Regions = 1,
            Scheduling = 2,
            History = 3,
            Accounts = 4,
            AdminDashboard = 6,
            Dashboard = 7,
            MyProfile = 10,
            Role,
            Provider,
            RequestData,
            SendOrder,
            Vendersinfo,
            Profession,
            EmailLogs = 18,
            HaloAdministrators,
            HaloUsers,
            CancelledHistory,
            ProviderLocation = 23,
            HaloEmployee,
            HaloWorkPlace,
            PatientRecords,
            BlockedHistory,
            Invoicing = 29,
            SMSLogs
        }
        //private readonly HalloDocDBContext _db;
        private readonly IAdminPartialsRepo _IAdminPartialsRepo;
        private readonly IPatientDashboardRepo _IPatientDashboardRepo;
        private readonly IContactRepository _ContactRepository;
        private readonly IJwtAuthInterface _JwtAuth;

        public AdminPartialsController(HalloDocDBContext db, IAdminPartialsRepo IAdminPartialsRepo, IPatientDashboardRepo iPatientDashboardRepo, IJwtAuthInterface jwtAuth, IContactRepository contactRepository)
        {
            //_db = db;
            _IAdminPartialsRepo = IAdminPartialsRepo;
            _IPatientDashboardRepo = iPatientDashboardRepo;
            _JwtAuth = jwtAuth;
            _ContactRepository = contactRepository;
        }

        #region StatusWiseRequests

        [RoleAuth((int)adminRoles.Dashboard)]
        [HttpGet]
        public async Task<IActionResult> AdminDashBoardMain()
        {
            try
            {
                DataCount datacount = await _IAdminPartialsRepo.AdminDashBoardMain();
                return PartialView("/Views/AdminPartials/_AdminDashBoard.cshtml", datacount);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> NewRequests(string? search, int? regid, int? reqType, int? PageNumber)
        {
            HttpContext.Session.SetString("CurrentRequest", "1");
            NewRequestCombineViewModel combineModel = await _IAdminPartialsRepo.NewRequests(search, regid, reqType, PageNumber);
            return PartialView("/Views/AdminPartials/_NewTablePartial.cshtml", combineModel);
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> PendingRequests(string? search, int? regid, int? reqType, int? PageNumber)
        {
            try
            {
                HttpContext.Session.SetString("CurrentRequest", "2");
                PendingRequestCombine Pendingquery = await _IAdminPartialsRepo.PendingRequests(search, regid, reqType, PageNumber);
                return PartialView("/Views/AdminPartials/_PendingTablePartial.cshtml", Pendingquery);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> ActiveRequests(string? search, int? regid, int? reqType, int? PageNumber)
        {
            try
            {
                HttpContext.Session.SetString("CurrentRequest", "3");
                ActiveRequestCombine Activequery = await _IAdminPartialsRepo.ActiveRequests(search, regid, reqType, PageNumber);
                return PartialView("/Views/AdminPartials/_ActiveTablePartial.cshtml", Activequery);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> ConcludeRequests(string? search, int? regid, int? reqType, int? PageNumber)
        {
            try
            {

                HttpContext.Session.SetString("CurrentRequest", "4");
                ConcludeRequestCombine Concludequery = await _IAdminPartialsRepo.ConcludeRequests(search, regid, reqType, PageNumber);
                return PartialView("/Views/AdminPartials/_ConcludeTablePartialView.cshtml", Concludequery);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> CloseRequests(string? search, int? regid, int? reqType, int? PageNumber)
        {
            try
            {
                HttpContext.Session.SetString("CurrentRequest", "5");
                ToCloseCombine ToClosequery = await _IAdminPartialsRepo.CloseRequests(search, regid, reqType, PageNumber);
                return PartialView("/Views/AdminPartials/_ToCloseTablePartialView.cshtml", ToClosequery);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> UnPaidRequests(string? search, int? regid, int? reqType, int? PageNumber)
        {
            try
            {
                HttpContext.Session.SetString("CurrentRequest", "6");
                UnpaidCombine Unpaidquery = await _IAdminPartialsRepo.UnPaidRequests(search, regid, reqType, PageNumber);
                return PartialView("/Views/AdminPartials/_UnPaidTablePartialView.cshtml", Unpaidquery);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }
        #endregion

        #region DashBoardActions

        public async Task<IActionResult> GetPhysicianByRegion(int RegionId)
        {
            try
            {
                IList<Physician> physicianName = await _IAdminPartialsRepo.GetPhysicianByRegion(RegionId);

                Console.Write(physicianName);
                return Json(new { physicianName = physicianName });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
            //return List of the physicians 
        }

        [RoleAuth((int)adminRoles.ProviderLocation)]
        public async Task<IActionResult> LoadProviderLocationPartial()
        {
            try
            {
                var token = Request.Cookies["Jwt"];
                if (token == null)
                {
                    return RedirectToAction("LoginPage", "PatientSide");
                }
                UserDataViewModel jwtData = _JwtAuth.AccessData(token);
                if (jwtData.UserId == null)
                {
                    return RedirectToAction("LoginPage", "PatientSide");
                }
                IEnumerable<Physician>? phy = await _IAdminPartialsRepo.LoadProviderLocationPartial(int.Parse(jwtData.UserId));
                return await Task.Run(() => PartialView("/Views/AdminPartials/_LoadProviderLocationPartial.cshtml", phy));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> ViewNewCases(int requestid)
        {
            try
            {
                if (await _IAdminPartialsRepo.IsDeleted(requestid))
                {
                    return RedirectToAction("Index", "Home");
                }
                ViewCasesViewModel patientDetails = await _IAdminPartialsRepo.ViewNewCases(requestid);
                if (patientDetails == null)
                {
                    return RedirectToAction("AdminDashBoardMain");
                }
                HttpContext.Session.SetString("reqid", requestid.ToString());
                return PartialView("/Views/AdminPartials/_ViewNewCasesPartialView.cshtml", patientDetails);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ViewNewCasespost(ViewCasesViewModel obj)
        {
            try
            {
                var reqid = HttpContext.Session.GetString("reqid");
                if (reqid == null)
                {
                    return RedirectToAction("AdminDashBoardMain");
                }
                bool status = await _IAdminPartialsRepo.ViewNewCasespost(obj, int.Parse(reqid));
                return Json(new { status = status, reqid = reqid });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
        }

        [RoleAuth((int)adminRoles.Dashboard)]
        public async Task<IActionResult> ShowViewNotes(int requestid)
        {

halloDocMvc/Controllers/AdminSiteController.cs
using AdminHalloDoc.Controllers.Login;
using HalloDoc.BAL.Interface;
using HalloDoc.DAL.Data;
using HalloDoc.DAL.DataModels;
using HalloDoc.DAL.ViewModals;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Diagnostics.Tracing.Parsers.AspNet;

namespace hellodocsrsmvc.Controllers
{

    //[adminauthentication]
    [AdminAuth("admin")]
    public class AdminSiteController : Controller
    {
        //private readonly HalloDocDBContext _db;
        private readonly IJwtAuthInterface _JwtAuth;
        private readonly IContactRepository _contactRepository;

        public AdminSiteController(HalloDocDBContext db, IJwtAuthInterface jwtAuth, IContactRepository contactRepository)
        {
            _JwtAuth = jwtAuth;
            _contactRepository = contactRepository;
        }
        //[adminauthentication]
        [RoleAuth(1)]
        public async Task<IActionResult> AdminDashBoard()
        {
            var token = Request.Cookies["Jwt"];
            if (token == null)
            {
                return View();
            }
            UserDataViewModel jwtData = _JwtAuth.AccessData(token);
            if (jwtData == null)
            {
                return RedirectToAction("LoginPage", "PatientSide");
            }
            if (jwtData.UserId == null)
            {
                return RedirectToAction("LoginPage", "PatientSide");
            }
            var admindata = _contactRepository.Admin(jwtData.UserId);
            if (admindata == null)
            {
                ViewBag.firstname = jwtData.FirstName;
                ViewBag.lastname = jwtData.LastName;
            }
            else
            {
                ViewBag.firstname = admindata.Firstname;
                ViewBag.lastname = admindata.Lastname;
            }
            IEnumerable<Rolemenu>? model = await _contactRepository.getRoleMenu(int.Parse(jwtData.roleid));
            return View(model);
        }
        public IActionResult LoadAdminDashBoardPartial()
        {
            return PartialView("/Views/AdminPartials/_AdminDashBoard.cshtml");
        }
        public IActionResult LoadProviderLocationPartial()
        {
            return PartialView("/Views/AdminPartials/_LoadProviderLocationPartial.cshtml");
        }

    }
}

halloDocMvc/Views/AdminSite/AdminDashboard.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
    Layout = "AdminHeader";
        // <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.0.0/css/flag-icons.min.css" />
}
@section styles {

    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/patientSubmitRequestStyle.css">
    <link rel="stylesheet" href="/css/sidebarcss.css">
    <link rel="stylesheet" href="/css/adminDashBoardcss.css">
}

<div class="loader"></div>
@* partial view will be loaded here *@
<div class="admin-data-container" style="overflow-x: hidden">
</div>

@section scriptdashboard {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    @* load all partial view on click events top-7 *@
    <script>
        $(document).ajaxSend(function () {
            $(".loader").fadeIn(250);
        });
        $(document).ajaxComplete(function () {
            $(".loader").fadeOut(250);
        });
        $(document).ready(function () {
            // $('.loader').bind('ajaxStart', function () {
            //     $(this).show();
            //     $(".admin-data-container").hide();
            // }).bind('ajaxStop', function () {
            //     $(".admin-data-container").show();
            //     $(this).hide();
            // });
            $("#AdminDash").click();
        })
        $("#AdminDash").click(function () {

            localStorage.setItem("CurrentClicked", "#AdminDash")

            $(".admin-data-container").load('@Url.Action("AdminDashBoardMain", "AdminPartials")', function () {
                // $.ajax({
                //     url: '/AdminPartials/LoadRegion',
                //     method: 'POST',
                //     success: function (response) {
                //         $('#RegionList').empty();
                //         $('#RegionList').append('<option value="-1" Selected>All Region</option>')
                //         response.region.forEach(function (regionname) {
                //             $('#RegionList').append('<option value="' + regionname.regionid + '">' + regionname.name + '</option>')
                //         })
                //     }
                // });
            });
        })
        $("#AdminProfileEdit").click(function () {
            localStorage.setItem("profileEdit", "admin");
            $(".admin-data-container").load('@Url.Action("AdminProfile", "AdminPartials")', function () {
                // load status
                $.ajax({
                    url: '/AdminPartials/LoadStatus',
                    method: 'POST',
                    success: function (response) {
                        response.forEach(function (status) {
                            if (($('.loadstatus').val()) == status.statusId) {
                            }
                            else {
                                $('.loadstatus').append('<option value="' + status.statusId + '">' + status.statusname + '</option>')
                            }
                        });
                    }
                })
                // load role
                $.ajax({
                    url: '/AdminPartials/LoadRole',
                    method: 'POST',
                    success: function (response) {
                        response.forEach(function (role) {
                            if ($('.loadRole').val() == role.roleid) {

                            }
                            else if (role.accounttype == 2) {
                                $('.loadRole').append('<option value="' + role.roleid + '">' + role.name + '</option>')
                            }
                        });
                    }
                });
                // load region
                $.ajax({
                    url: '/AdminPartials/LoadRegion',
                    method: 'POST',
                    success: function (response) {
                        response.region.forEach(function (regionname) {
                            if ($('.loadRegion').val() == regionname.regionid) {

                            } else {
                                $('.loadRegion').append('<option value="' + regionname.regionid + '">' + regionname.name + '</option>')
                            }
                        });
                    }
                });
            });
        });
        function BackDoc() {
            var actionmethod = localStorage.getItem("BackDoc");
            var userid = localStorage.getItem("userid");
            $(".admin-data-container").load('/AdminPartials/' + actionmethod + '?userid=' + userid)
        }
    </script>

}